// DO NOT EDIT, generated by goctl
package handler

import (
	"net/http"

	open "hello/internal/handler/open"
	"hello/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/open/register",
			Handler: open.RegisterHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/open/authorization",
			Handler: open.AuthorizationHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/open/verify",
			Handler: open.VerifyHandler(serverCtx),
		},
	})
}
