// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory.proto

package inventory

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type StockInfo struct {
	StockId              int32    `protobuf:"varint,1,opt,name=StockId,proto3" json:"StockId,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockInfo) Reset()         { *m = StockInfo{} }
func (m *StockInfo) String() string { return proto.CompactTextString(m) }
func (*StockInfo) ProtoMessage()    {}
func (*StockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{1}
}

func (m *StockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockInfo.Unmarshal(m, b)
}
func (m *StockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockInfo.Marshal(b, m, deterministic)
}
func (m *StockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockInfo.Merge(m, src)
}
func (m *StockInfo) XXX_Size() int {
	return xxx_messageInfo_StockInfo.Size(m)
}
func (m *StockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StockInfo proto.InternalMessageInfo

func (m *StockInfo) GetStockId() int32 {
	if m != nil {
		return m.StockId
	}
	return 0
}

func (m *StockInfo) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type SellInfo struct {
	StockId              int32    `protobuf:"varint,1,opt,name=StockId,proto3" json:"StockId,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	TrustSn              string   `protobuf:"bytes,3,opt,name=trustSn,proto3" json:"trustSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellInfo) Reset()         { *m = SellInfo{} }
func (m *SellInfo) String() string { return proto.CompactTextString(m) }
func (*SellInfo) ProtoMessage()    {}
func (*SellInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{2}
}

func (m *SellInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfo.Unmarshal(m, b)
}
func (m *SellInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfo.Marshal(b, m, deterministic)
}
func (m *SellInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfo.Merge(m, src)
}
func (m *SellInfo) XXX_Size() int {
	return xxx_messageInfo_SellInfo.Size(m)
}
func (m *SellInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfo proto.InternalMessageInfo

func (m *SellInfo) GetStockId() int32 {
	if m != nil {
		return m.StockId
	}
	return 0
}

func (m *SellInfo) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *SellInfo) GetTrustSn() string {
	if m != nil {
		return m.TrustSn
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "inventory.Empty")
	proto.RegisterType((*StockInfo)(nil), "inventory.StockInfo")
	proto.RegisterType((*SellInfo)(nil), "inventory.SellInfo")
}

func init() { proto.RegisterFile("inventory.proto", fileDescriptor_7173caedb7c6ae96) }

var fileDescriptor_7173caedb7c6ae96 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xcc, 0x2b, 0x4b,
	0xcd, 0x2b, 0xc9, 0x2f, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94, 0x54, 0x2a, 0x99, 0x73, 0x71, 0x06, 0x97, 0xe4, 0x27,
	0x67, 0x7b, 0xe6, 0xa5, 0xe5, 0x0b, 0x49, 0x70, 0xb1, 0x43, 0x38, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x30, 0xae, 0x90, 0x00, 0x17, 0x73, 0x5e, 0x69, 0xae, 0x04, 0x13, 0x58, 0x14,
	0xc4, 0x54, 0x0a, 0xe0, 0xe2, 0x08, 0x4e, 0xcd, 0xc9, 0x21, 0x55, 0x1f, 0x48, 0x6d, 0x49, 0x51,
	0x69, 0x71, 0x49, 0x70, 0x9e, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0x6b, 0x74, 0x8d,
	0x91, 0x0b, 0xe1, 0x42, 0x21, 0x03, 0x2e, 0xb6, 0xe0, 0xd4, 0x12, 0xcf, 0xbc, 0x32, 0x21, 0x11,
	0x3d, 0x84, 0x47, 0xe0, 0x6e, 0x95, 0x12, 0x40, 0x12, 0x05, 0x7b, 0x45, 0xc8, 0x9c, 0x8b, 0xd3,
	0x33, 0xaf, 0xcc, 0x25, 0xb5, 0x24, 0x31, 0x33, 0x07, 0x87, 0x26, 0xac, 0xa2, 0x42, 0xba, 0x5c,
	0x2c, 0x20, 0xaf, 0x08, 0x09, 0x23, 0xcb, 0x42, 0xfd, 0x86, 0xc5, 0x1e, 0x7d, 0x2e, 0xb6, 0xa0,
	0xd4, 0xa4, 0xc4, 0xe4, 0x6c, 0x22, 0x35, 0x24, 0xb1, 0x81, 0x83, 0xdf, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0xf4, 0x07, 0xaa, 0x91, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InventoryClient interface {
	SetInv(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Empty, error)
	InvDetail(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*StockInfo, error)
	Sell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error)
	Reback(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error)
}

type inventoryClient struct {
	cc *grpc.ClientConn
}

func NewInventoryClient(cc *grpc.ClientConn) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) SetInv(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/inventory.inventory/SetInv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) InvDetail(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*StockInfo, error) {
	out := new(StockInfo)
	err := c.cc.Invoke(ctx, "/inventory.inventory/InvDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) Sell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/inventory.inventory/Sell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) Reback(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/inventory.inventory/Reback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
type InventoryServer interface {
	SetInv(context.Context, *StockInfo) (*Empty, error)
	InvDetail(context.Context, *StockInfo) (*StockInfo, error)
	Sell(context.Context, *SellInfo) (*Empty, error)
	Reback(context.Context, *SellInfo) (*Empty, error)
}

// UnimplementedInventoryServer can be embedded to have forward compatible implementations.
type UnimplementedInventoryServer struct {
}

func (*UnimplementedInventoryServer) SetInv(ctx context.Context, req *StockInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInv not implemented")
}
func (*UnimplementedInventoryServer) InvDetail(ctx context.Context, req *StockInfo) (*StockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvDetail not implemented")
}
func (*UnimplementedInventoryServer) Sell(ctx context.Context, req *SellInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sell not implemented")
}
func (*UnimplementedInventoryServer) Reback(ctx context.Context, req *SellInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reback not implemented")
}

func RegisterInventoryServer(s *grpc.Server, srv InventoryServer) {
	s.RegisterService(&_Inventory_serviceDesc, srv)
}

func _Inventory_SetInv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).SetInv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.inventory/SetInv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).SetInv(ctx, req.(*StockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_InvDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).InvDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.inventory/InvDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).InvDetail(ctx, req.(*StockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_Sell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).Sell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.inventory/Sell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).Sell(ctx, req.(*SellInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_Reback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).Reback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.inventory/Reback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).Reback(ctx, req.(*SellInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inventory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetInv",
			Handler:    _Inventory_SetInv_Handler,
		},
		{
			MethodName: "InvDetail",
			Handler:    _Inventory_InvDetail_Handler,
		},
		{
			MethodName: "Sell",
			Handler:    _Inventory_Sell_Handler,
		},
		{
			MethodName: "Reback",
			Handler:    _Inventory_Reback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}
