// Code generated by goctl. DO NOT EDIT!
// Source: operation.proto

package server

import (
	"context"
	"github.com/tal-tech/go-zero/core/stores/cache"
	"gorm.io/gorm"
	"stockexchange/rpc/operation/internal/svc"

	"stockexchange/rpc/operation/internal/logic"
	"stockexchange/rpc/operation/operation"
)

type OperationServer struct {
	svcCtx   *svc.ServiceContext
	DbEngine *gorm.DB
	Cache    cache.CacheConf
}

func NewOperationServer(svcCtx *svc.ServiceContext) *OperationServer {
	return &OperationServer{
		svcCtx: svcCtx,
	}
}

func (s *OperationServer) GetFavList(ctx context.Context, in *operation.UserFavRequest) (*operation.UserFavListResponse, error) {
	l := logic.NewGetFavListLogic(ctx, s.svcCtx)
	return l.GetFavList(in)
}

func (s *OperationServer) AddUserFav(ctx context.Context, in *operation.UserFavRequest) (*operation.Empty, error) {
	l := logic.NewAddUserFavLogic(ctx, s.svcCtx)
	return l.AddUserFav(in)
}

func (s *OperationServer) DeleteUserFav(ctx context.Context, in *operation.UserFavRequest) (*operation.Empty, error) {
	l := logic.NewDeleteUserFavLogic(ctx, s.svcCtx)
	return l.DeleteUserFav(in)
}

func (s *OperationServer) GetUserFavDetail(ctx context.Context, in *operation.UserFavRequest) (*operation.Empty, error) {
	l := logic.NewGetUserFavDetailLogic(ctx, s.svcCtx)
	return l.GetUserFavDetail(in)
}
