// Code generated by goctl. DO NOT EDIT.
package types

type DetailMeta struct {
	Msg    string `json:"msg""`
	Status int16  `json:"status"`
}

type ReqUserFav struct {
	UserId  string `json:"userid"`
	StockId string `json:"stockid"`
}

type ReqStockFav struct {
	UserId  string `json:"userid"`
	StockId string `json:"stockid"`
}

type RespFavDetail struct {
	DetailMeta
}

type FavMessage struct {
	Total   int      `json:"total""`
	FavList []string `json:"favlist"`
}

type RespFavList struct {
	FavMessage
	DetailMeta
}
