// Code generated by goctl. DO NOT EDIT.
package types

type RespUserLogin struct {
	LoginMessage
	LoginMeta
}

type ReqUserLogin struct {
	Email    string `json:"email" binding:"required, email"`
	Password string `json:"password" binding:"required, min=6, max=10"`
}

type ReqUserRegister struct {
	UserName string `json:"username" binding:"required,max=10"`
	Password string `json:"password" binding:"required, min=6, max=10"`
	Email    string `json:"email" binding:"required, email"`
	Gender   string `json:"password" binding:"required"`
	Code     string `json:"code" binding:"required,min=6,max=6"`
}

type LoginMessage struct {
	Id          int64  `json:"id"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	Gender      string `json:"gender"`
	Role        int32  `json:"role"`
	AccessToken string `json:"token"`
}

type LoginMeta struct {
	Msg    string `json:"msg""`
	Status int16  `json:"status"`
}
