// Code generated by goctl. DO NOT EDIT.
package types

type RespUserLogin struct {
	LoginMessage `json:"message"`
	LoginMeta    `json:"meta"`
}

type ReqUserLogin struct {
	Email    string `json:"email" binding:"required, email"`
	Password string `json:"password" binding:"required, min=6, max=10"`
}

type LoginMessage struct {
	Id          int64  `json:"id"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	Gender      string `json:"gender"`
	Role        int32  `json:"role"`
	AccessToken string `json:"token"`
}

type LoginMeta struct {
	Msg    string `json:"msg""`
	Status int16  `json:"status"`
}
