// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"stockexchange/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

// routers.go 是路由，根据 request Method 和 url 把请求分发到对应到的 handler 上，
// handler 内部会去调用对应的 logic.
// logic 文件内是我们注入代码逻辑的地方
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/users/id/:id",
				Handler: DeleteUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/id/:id",
				Handler: UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/id/:id",
				Handler: GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: GetAllUsersHandler(serverCtx),
			},
		},
	)
}
