// Code generated by goctl. DO NOT EDIT!
// Source: operation.proto

package operationclient

import (
	"context"

	"stockexchange/rpc/operation/operation"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty               = operation.Empty
	UserFavListResponse = operation.UserFavListResponse
	UserFavRequest      = operation.UserFavRequest
	UserFavResponse     = operation.UserFavResponse

	Operation interface {
		GetFavList(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavListResponse, error)
		AddUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
		DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
		GetUserFavDetail(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultOperation struct {
		cli zrpc.Client
	}
)

func NewOperation(cli zrpc.Client) Operation {
	return &defaultOperation{
		cli: cli,
	}
}

func (m *defaultOperation) GetFavList(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavListResponse, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.GetFavList(ctx, in, opts...)
}

func (m *defaultOperation) AddUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.AddUserFav(ctx, in, opts...)
}

func (m *defaultOperation) DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.DeleteUserFav(ctx, in, opts...)
}

func (m *defaultOperation) GetUserFavDetail(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := operation.NewOperationClient(m.cli.Conn())
	return client.GetUserFavDetail(ctx, in, opts...)
}
