// Code generated by goctl. DO NOT EDIT!
// Source: inventory.proto

package inventoryclient

import (
	"context"

	"stockexchange/rpc/inventory/inventory"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty     = inventory.Empty
	SellInfo  = inventory.SellInfo
	StockInfo = inventory.StockInfo

	Inventory interface {
		SetInv(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Empty, error)
		InvDetail(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*StockInfo, error)
		Sell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error)
		Reback(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultInventory struct {
		cli zrpc.Client
	}
)

func NewInventory(cli zrpc.Client) Inventory {
	return &defaultInventory{
		cli: cli,
	}
}

func (m *defaultInventory) SetInv(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.SetInv(ctx, in, opts...)
}

func (m *defaultInventory) InvDetail(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*StockInfo, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.InvDetail(ctx, in, opts...)
}

func (m *defaultInventory) Sell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.Sell(ctx, in, opts...)
}

func (m *defaultInventory) Reback(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.Reback(ctx, in, opts...)
}
