// DO NOT EDIT, generated by goctl
package types

type UserOptReq struct {
	Email  string `json:"Email" form:"Email"`
	Passwd string `json:"passwd" form:"passwd"`
}

type UserOptResp struct {
	Id    uint   `json:"id"`
	Token string `json:"token"`
}

type VerifyReq struct {
	Ticket string `json:"ticket" form:"ticket"`
}

type VerifyResp struct {
	Data string `json:"data"`
}
