// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type IdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserAccountResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Account              float32  `protobuf:"fixed32,2,opt,name=account,proto3" json:"account,omitempty"`
	MarketValue          float32  `protobuf:"fixed32,3,opt,name=marketValue,proto3" json:"marketValue,omitempty"`
	Available            float32  `protobuf:"fixed32,4,opt,name=available,proto3" json:"available,omitempty"`
	ProfitAndLoss        float32  `protobuf:"fixed32,5,opt,name=profitAndLoss,proto3" json:"profitAndLoss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAccountResponse) Reset()         { *m = UserAccountResponse{} }
func (m *UserAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UserAccountResponse) ProtoMessage()    {}
func (*UserAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *UserAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAccountResponse.Unmarshal(m, b)
}
func (m *UserAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAccountResponse.Marshal(b, m, deterministic)
}
func (m *UserAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAccountResponse.Merge(m, src)
}
func (m *UserAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UserAccountResponse.Size(m)
}
func (m *UserAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserAccountResponse proto.InternalMessageInfo

func (m *UserAccountResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserAccountResponse) GetAccount() float32 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *UserAccountResponse) GetMarketValue() float32 {
	if m != nil {
		return m.MarketValue
	}
	return 0
}

func (m *UserAccountResponse) GetAvailable() float32 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *UserAccountResponse) GetProfitAndLoss() float32 {
	if m != nil {
		return m.ProfitAndLoss
	}
	return 0
}

type CreateUserAccountInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Account              float32  `protobuf:"fixed32,2,opt,name=account,proto3" json:"account,omitempty"`
	MarketValue          float32  `protobuf:"fixed32,3,opt,name=marketValue,proto3" json:"marketValue,omitempty"`
	Available            float32  `protobuf:"fixed32,4,opt,name=available,proto3" json:"available,omitempty"`
	ProfitAndLoss        float32  `protobuf:"fixed32,5,opt,name=profitAndLoss,proto3" json:"profitAndLoss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserAccountInfo) Reset()         { *m = CreateUserAccountInfo{} }
func (m *CreateUserAccountInfo) String() string { return proto.CompactTextString(m) }
func (*CreateUserAccountInfo) ProtoMessage()    {}
func (*CreateUserAccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *CreateUserAccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserAccountInfo.Unmarshal(m, b)
}
func (m *CreateUserAccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserAccountInfo.Marshal(b, m, deterministic)
}
func (m *CreateUserAccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserAccountInfo.Merge(m, src)
}
func (m *CreateUserAccountInfo) XXX_Size() int {
	return xxx_messageInfo_CreateUserAccountInfo.Size(m)
}
func (m *CreateUserAccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserAccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserAccountInfo proto.InternalMessageInfo

func (m *CreateUserAccountInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateUserAccountInfo) GetAccount() float32 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *CreateUserAccountInfo) GetMarketValue() float32 {
	if m != nil {
		return m.MarketValue
	}
	return 0
}

func (m *CreateUserAccountInfo) GetAvailable() float32 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *CreateUserAccountInfo) GetProfitAndLoss() float32 {
	if m != nil {
		return m.ProfitAndLoss
	}
	return 0
}

type UpdateUserAccountInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Account              float32  `protobuf:"fixed32,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserAccountInfo) Reset()         { *m = UpdateUserAccountInfo{} }
func (m *UpdateUserAccountInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateUserAccountInfo) ProtoMessage()    {}
func (*UpdateUserAccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *UpdateUserAccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserAccountInfo.Unmarshal(m, b)
}
func (m *UpdateUserAccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserAccountInfo.Marshal(b, m, deterministic)
}
func (m *UpdateUserAccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserAccountInfo.Merge(m, src)
}
func (m *UpdateUserAccountInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateUserAccountInfo.Size(m)
}
func (m *UpdateUserAccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserAccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserAccountInfo proto.InternalMessageInfo

func (m *UpdateUserAccountInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateUserAccountInfo) GetAccount() float32 {
	if m != nil {
		return m.Account
	}
	return 0
}

type DeleteUserAccountInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserAccountInfo) Reset()         { *m = DeleteUserAccountInfo{} }
func (m *DeleteUserAccountInfo) String() string { return proto.CompactTextString(m) }
func (*DeleteUserAccountInfo) ProtoMessage()    {}
func (*DeleteUserAccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *DeleteUserAccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserAccountInfo.Unmarshal(m, b)
}
func (m *DeleteUserAccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserAccountInfo.Marshal(b, m, deterministic)
}
func (m *DeleteUserAccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserAccountInfo.Merge(m, src)
}
func (m *DeleteUserAccountInfo) XXX_Size() int {
	return xxx_messageInfo_DeleteUserAccountInfo.Size(m)
}
func (m *DeleteUserAccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserAccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserAccountInfo proto.InternalMessageInfo

func (m *DeleteUserAccountInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteUserAccountResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserAccountResponse) Reset()         { *m = DeleteUserAccountResponse{} }
func (m *DeleteUserAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserAccountResponse) ProtoMessage()    {}
func (*DeleteUserAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *DeleteUserAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserAccountResponse.Unmarshal(m, b)
}
func (m *DeleteUserAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserAccountResponse.Merge(m, src)
}
func (m *DeleteUserAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserAccountResponse.Size(m)
}
func (m *DeleteUserAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserAccountResponse proto.InternalMessageInfo

func (m *DeleteUserAccountResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PageInfo struct {
	Pn                   uint32   `protobuf:"varint,1,opt,name=pn,proto3" json:"pn,omitempty"`
	PSize                uint32   `protobuf:"varint,2,opt,name=pSize,proto3" json:"pSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPn() uint32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *PageInfo) GetPSize() uint32 {
	if m != nil {
		return m.PSize
	}
	return 0
}

type UserAccountListResponse struct {
	Total                int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*UserAccountResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserAccountListResponse) Reset()         { *m = UserAccountListResponse{} }
func (m *UserAccountListResponse) String() string { return proto.CompactTextString(m) }
func (*UserAccountListResponse) ProtoMessage()    {}
func (*UserAccountListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *UserAccountListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAccountListResponse.Unmarshal(m, b)
}
func (m *UserAccountListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAccountListResponse.Marshal(b, m, deterministic)
}
func (m *UserAccountListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAccountListResponse.Merge(m, src)
}
func (m *UserAccountListResponse) XXX_Size() int {
	return xxx_messageInfo_UserAccountListResponse.Size(m)
}
func (m *UserAccountListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAccountListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserAccountListResponse proto.InternalMessageInfo

func (m *UserAccountListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserAccountListResponse) GetData() []*UserAccountResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

// 持仓相关
type HoldPositionRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoldPositionRequest) Reset()         { *m = HoldPositionRequest{} }
func (m *HoldPositionRequest) String() string { return proto.CompactTextString(m) }
func (*HoldPositionRequest) ProtoMessage()    {}
func (*HoldPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *HoldPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoldPositionRequest.Unmarshal(m, b)
}
func (m *HoldPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoldPositionRequest.Marshal(b, m, deterministic)
}
func (m *HoldPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldPositionRequest.Merge(m, src)
}
func (m *HoldPositionRequest) XXX_Size() int {
	return xxx_messageInfo_HoldPositionRequest.Size(m)
}
func (m *HoldPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HoldPositionRequest proto.InternalMessageInfo

func (m *HoldPositionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type HoldPositionResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 int64    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	StockName            string   `protobuf:"bytes,4,opt,name=stockName,proto3" json:"stockName,omitempty"`
	Number               int32    `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	Cost                 float32  `protobuf:"fixed32,6,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoldPositionResponse) Reset()         { *m = HoldPositionResponse{} }
func (m *HoldPositionResponse) String() string { return proto.CompactTextString(m) }
func (*HoldPositionResponse) ProtoMessage()    {}
func (*HoldPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *HoldPositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoldPositionResponse.Unmarshal(m, b)
}
func (m *HoldPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoldPositionResponse.Marshal(b, m, deterministic)
}
func (m *HoldPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldPositionResponse.Merge(m, src)
}
func (m *HoldPositionResponse) XXX_Size() int {
	return xxx_messageInfo_HoldPositionResponse.Size(m)
}
func (m *HoldPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HoldPositionResponse proto.InternalMessageInfo

func (m *HoldPositionResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HoldPositionResponse) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *HoldPositionResponse) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *HoldPositionResponse) GetStockName() string {
	if m != nil {
		return m.StockName
	}
	return ""
}

func (m *HoldPositionResponse) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *HoldPositionResponse) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type CreateHoldPositionRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	StockName            string   `protobuf:"bytes,3,opt,name=stockName,proto3" json:"stockName,omitempty"`
	Number               int32    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Cost                 float32  `protobuf:"fixed32,5,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHoldPositionRequest) Reset()         { *m = CreateHoldPositionRequest{} }
func (m *CreateHoldPositionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHoldPositionRequest) ProtoMessage()    {}
func (*CreateHoldPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{11}
}

func (m *CreateHoldPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHoldPositionRequest.Unmarshal(m, b)
}
func (m *CreateHoldPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHoldPositionRequest.Marshal(b, m, deterministic)
}
func (m *CreateHoldPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHoldPositionRequest.Merge(m, src)
}
func (m *CreateHoldPositionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHoldPositionRequest.Size(m)
}
func (m *CreateHoldPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHoldPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHoldPositionRequest proto.InternalMessageInfo

func (m *CreateHoldPositionRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *CreateHoldPositionRequest) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *CreateHoldPositionRequest) GetStockName() string {
	if m != nil {
		return m.StockName
	}
	return ""
}

func (m *CreateHoldPositionRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *CreateHoldPositionRequest) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type UpdateHoldPositionRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	StockName            string   `protobuf:"bytes,3,opt,name=stockName,proto3" json:"stockName,omitempty"`
	Number               int32    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Cost                 float32  `protobuf:"fixed32,5,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateHoldPositionRequest) Reset()         { *m = UpdateHoldPositionRequest{} }
func (m *UpdateHoldPositionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateHoldPositionRequest) ProtoMessage()    {}
func (*UpdateHoldPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{12}
}

func (m *UpdateHoldPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHoldPositionRequest.Unmarshal(m, b)
}
func (m *UpdateHoldPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHoldPositionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateHoldPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHoldPositionRequest.Merge(m, src)
}
func (m *UpdateHoldPositionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHoldPositionRequest.Size(m)
}
func (m *UpdateHoldPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHoldPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHoldPositionRequest proto.InternalMessageInfo

func (m *UpdateHoldPositionRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *UpdateHoldPositionRequest) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *UpdateHoldPositionRequest) GetStockName() string {
	if m != nil {
		return m.StockName
	}
	return ""
}

func (m *UpdateHoldPositionRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *UpdateHoldPositionRequest) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type DeleteHoldPositionRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHoldPositionRequest) Reset()         { *m = DeleteHoldPositionRequest{} }
func (m *DeleteHoldPositionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHoldPositionRequest) ProtoMessage()    {}
func (*DeleteHoldPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{13}
}

func (m *DeleteHoldPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHoldPositionRequest.Unmarshal(m, b)
}
func (m *DeleteHoldPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHoldPositionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHoldPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHoldPositionRequest.Merge(m, src)
}
func (m *DeleteHoldPositionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHoldPositionRequest.Size(m)
}
func (m *DeleteHoldPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHoldPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHoldPositionRequest proto.InternalMessageInfo

func (m *DeleteHoldPositionRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *DeleteHoldPositionRequest) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

type DeleteHoldPositionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHoldPositionResponse) Reset()         { *m = DeleteHoldPositionResponse{} }
func (m *DeleteHoldPositionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteHoldPositionResponse) ProtoMessage()    {}
func (*DeleteHoldPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{14}
}

func (m *DeleteHoldPositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHoldPositionResponse.Unmarshal(m, b)
}
func (m *DeleteHoldPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHoldPositionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteHoldPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHoldPositionResponse.Merge(m, src)
}
func (m *DeleteHoldPositionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteHoldPositionResponse.Size(m)
}
func (m *DeleteHoldPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHoldPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHoldPositionResponse proto.InternalMessageInfo

func (m *DeleteHoldPositionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UserHoldPositionRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHoldPositionRequest) Reset()         { *m = UserHoldPositionRequest{} }
func (m *UserHoldPositionRequest) String() string { return proto.CompactTextString(m) }
func (*UserHoldPositionRequest) ProtoMessage()    {}
func (*UserHoldPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{15}
}

func (m *UserHoldPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHoldPositionRequest.Unmarshal(m, b)
}
func (m *UserHoldPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHoldPositionRequest.Marshal(b, m, deterministic)
}
func (m *UserHoldPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHoldPositionRequest.Merge(m, src)
}
func (m *UserHoldPositionRequest) XXX_Size() int {
	return xxx_messageInfo_UserHoldPositionRequest.Size(m)
}
func (m *UserHoldPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHoldPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserHoldPositionRequest proto.InternalMessageInfo

func (m *UserHoldPositionRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

type HoldPositionListResponse struct {
	Total                int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*HoldPositionResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *HoldPositionListResponse) Reset()         { *m = HoldPositionListResponse{} }
func (m *HoldPositionListResponse) String() string { return proto.CompactTextString(m) }
func (*HoldPositionListResponse) ProtoMessage()    {}
func (*HoldPositionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{16}
}

func (m *HoldPositionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoldPositionListResponse.Unmarshal(m, b)
}
func (m *HoldPositionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoldPositionListResponse.Marshal(b, m, deterministic)
}
func (m *HoldPositionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldPositionListResponse.Merge(m, src)
}
func (m *HoldPositionListResponse) XXX_Size() int {
	return xxx_messageInfo_HoldPositionListResponse.Size(m)
}
func (m *HoldPositionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldPositionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HoldPositionListResponse proto.InternalMessageInfo

func (m *HoldPositionListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *HoldPositionListResponse) GetData() []*HoldPositionResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

// 委托相关
type TrustItemRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	Number               int32    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Cost                 float32  `protobuf:"fixed32,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Direction            uint32   `protobuf:"varint,6,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustItemRequest) Reset()         { *m = TrustItemRequest{} }
func (m *TrustItemRequest) String() string { return proto.CompactTextString(m) }
func (*TrustItemRequest) ProtoMessage()    {}
func (*TrustItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{17}
}

func (m *TrustItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustItemRequest.Unmarshal(m, b)
}
func (m *TrustItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustItemRequest.Marshal(b, m, deterministic)
}
func (m *TrustItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustItemRequest.Merge(m, src)
}
func (m *TrustItemRequest) XXX_Size() int {
	return xxx_messageInfo_TrustItemRequest.Size(m)
}
func (m *TrustItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrustItemRequest proto.InternalMessageInfo

func (m *TrustItemRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *TrustItemRequest) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *TrustItemRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *TrustItemRequest) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *TrustItemRequest) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type TrustInfoResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 int64    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Number               int32    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Cost                 float32  `protobuf:"fixed32,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Direction            uint32   `protobuf:"varint,6,opt,name=direction,proto3" json:"direction,omitempty"`
	DealNumber           int32    `protobuf:"varint,7,opt,name=dealNumber,proto3" json:"dealNumber,omitempty"`
	DealCost             float32  `protobuf:"fixed32,8,opt,name=dealCost,proto3" json:"dealCost,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	TrustSn              string   `protobuf:"bytes,10,opt,name=trustSn,proto3" json:"trustSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustInfoResponse) Reset()         { *m = TrustInfoResponse{} }
func (m *TrustInfoResponse) String() string { return proto.CompactTextString(m) }
func (*TrustInfoResponse) ProtoMessage()    {}
func (*TrustInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{18}
}

func (m *TrustInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustInfoResponse.Unmarshal(m, b)
}
func (m *TrustInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustInfoResponse.Marshal(b, m, deterministic)
}
func (m *TrustInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustInfoResponse.Merge(m, src)
}
func (m *TrustInfoResponse) XXX_Size() int {
	return xxx_messageInfo_TrustInfoResponse.Size(m)
}
func (m *TrustInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrustInfoResponse proto.InternalMessageInfo

func (m *TrustInfoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TrustInfoResponse) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *TrustInfoResponse) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *TrustInfoResponse) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *TrustInfoResponse) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *TrustInfoResponse) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *TrustInfoResponse) GetDealNumber() int32 {
	if m != nil {
		return m.DealNumber
	}
	return 0
}

func (m *TrustInfoResponse) GetDealCost() float32 {
	if m != nil {
		return m.DealCost
	}
	return 0
}

func (m *TrustInfoResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TrustInfoResponse) GetTrustSn() string {
	if m != nil {
		return m.TrustSn
	}
	return ""
}

type UserTrustInfoRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTrustInfoRequest) Reset()         { *m = UserTrustInfoRequest{} }
func (m *UserTrustInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserTrustInfoRequest) ProtoMessage()    {}
func (*UserTrustInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{19}
}

func (m *UserTrustInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTrustInfoRequest.Unmarshal(m, b)
}
func (m *UserTrustInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTrustInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserTrustInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTrustInfoRequest.Merge(m, src)
}
func (m *UserTrustInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserTrustInfoRequest.Size(m)
}
func (m *UserTrustInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTrustInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserTrustInfoRequest proto.InternalMessageInfo

func (m *UserTrustInfoRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *UserTrustInfoRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserTrustInfoRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type TrustListResponse struct {
	Total                int32                `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*TrustInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TrustListResponse) Reset()         { *m = TrustListResponse{} }
func (m *TrustListResponse) String() string { return proto.CompactTextString(m) }
func (*TrustListResponse) ProtoMessage()    {}
func (*TrustListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{20}
}

func (m *TrustListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustListResponse.Unmarshal(m, b)
}
func (m *TrustListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustListResponse.Marshal(b, m, deterministic)
}
func (m *TrustListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustListResponse.Merge(m, src)
}
func (m *TrustListResponse) XXX_Size() int {
	return xxx_messageInfo_TrustListResponse.Size(m)
}
func (m *TrustListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrustListResponse proto.InternalMessageInfo

func (m *TrustListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *TrustListResponse) GetData() []*TrustInfoResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type TrustInfoRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrustSn              string   `protobuf:"bytes,2,opt,name=trustSn,proto3" json:"trustSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustInfoRequest) Reset()         { *m = TrustInfoRequest{} }
func (m *TrustInfoRequest) String() string { return proto.CompactTextString(m) }
func (*TrustInfoRequest) ProtoMessage()    {}
func (*TrustInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{21}
}

func (m *TrustInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustInfoRequest.Unmarshal(m, b)
}
func (m *TrustInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustInfoRequest.Marshal(b, m, deterministic)
}
func (m *TrustInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustInfoRequest.Merge(m, src)
}
func (m *TrustInfoRequest) XXX_Size() int {
	return xxx_messageInfo_TrustInfoRequest.Size(m)
}
func (m *TrustInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrustInfoRequest proto.InternalMessageInfo

func (m *TrustInfoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TrustInfoRequest) GetTrustSn() string {
	if m != nil {
		return m.TrustSn
	}
	return ""
}

type UpdateTrustRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TrustSn              string   `protobuf:"bytes,3,opt,name=trustSn,proto3" json:"trustSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTrustRequest) Reset()         { *m = UpdateTrustRequest{} }
func (m *UpdateTrustRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTrustRequest) ProtoMessage()    {}
func (*UpdateTrustRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{22}
}

func (m *UpdateTrustRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTrustRequest.Unmarshal(m, b)
}
func (m *UpdateTrustRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTrustRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTrustRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTrustRequest.Merge(m, src)
}
func (m *UpdateTrustRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTrustRequest.Size(m)
}
func (m *UpdateTrustRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTrustRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTrustRequest proto.InternalMessageInfo

func (m *UpdateTrustRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTrustRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateTrustRequest) GetTrustSn() string {
	if m != nil {
		return m.TrustSn
	}
	return ""
}

type DeleteTrustRequest struct {
	// 保证委托删除正确
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 int64    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	TrustSn              string   `protobuf:"bytes,4,opt,name=trustSn,proto3" json:"trustSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTrustRequest) Reset()         { *m = DeleteTrustRequest{} }
func (m *DeleteTrustRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTrustRequest) ProtoMessage()    {}
func (*DeleteTrustRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{23}
}

func (m *DeleteTrustRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTrustRequest.Unmarshal(m, b)
}
func (m *DeleteTrustRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTrustRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTrustRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTrustRequest.Merge(m, src)
}
func (m *DeleteTrustRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTrustRequest.Size(m)
}
func (m *DeleteTrustRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTrustRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTrustRequest proto.InternalMessageInfo

func (m *DeleteTrustRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteTrustRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *DeleteTrustRequest) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *DeleteTrustRequest) GetTrustSn() string {
	if m != nil {
		return m.TrustSn
	}
	return ""
}

type DeleteTrustResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTrustResponse) Reset()         { *m = DeleteTrustResponse{} }
func (m *DeleteTrustResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTrustResponse) ProtoMessage()    {}
func (*DeleteTrustResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{24}
}

func (m *DeleteTrustResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTrustResponse.Unmarshal(m, b)
}
func (m *DeleteTrustResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTrustResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTrustResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTrustResponse.Merge(m, src)
}
func (m *DeleteTrustResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTrustResponse.Size(m)
}
func (m *DeleteTrustResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTrustResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTrustResponse proto.InternalMessageInfo

func (m *DeleteTrustResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type OrderItemRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	Number               int32    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Cost                 float32  `protobuf:"fixed32,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Direction            uint32   `protobuf:"varint,6,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItemRequest) Reset()         { *m = OrderItemRequest{} }
func (m *OrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*OrderItemRequest) ProtoMessage()    {}
func (*OrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{25}
}

func (m *OrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItemRequest.Unmarshal(m, b)
}
func (m *OrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItemRequest.Marshal(b, m, deterministic)
}
func (m *OrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItemRequest.Merge(m, src)
}
func (m *OrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_OrderItemRequest.Size(m)
}
func (m *OrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItemRequest proto.InternalMessageInfo

func (m *OrderItemRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *OrderItemRequest) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *OrderItemRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *OrderItemRequest) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *OrderItemRequest) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type OrderInfoResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 int64    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Number               int32    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Cost                 float32  `protobuf:"fixed32,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Direction            uint32   `protobuf:"varint,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	OrderSn              string   `protobuf:"bytes,8,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfoResponse) Reset()         { *m = OrderInfoResponse{} }
func (m *OrderInfoResponse) String() string { return proto.CompactTextString(m) }
func (*OrderInfoResponse) ProtoMessage()    {}
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{26}
}

func (m *OrderInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoResponse.Unmarshal(m, b)
}
func (m *OrderInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoResponse.Marshal(b, m, deterministic)
}
func (m *OrderInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoResponse.Merge(m, src)
}
func (m *OrderInfoResponse) XXX_Size() int {
	return xxx_messageInfo_OrderInfoResponse.Size(m)
}
func (m *OrderInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoResponse proto.InternalMessageInfo

func (m *OrderInfoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderInfoResponse) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *OrderInfoResponse) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *OrderInfoResponse) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *OrderInfoResponse) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *OrderInfoResponse) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *OrderInfoResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderInfoResponse) GetOrderSn() string {
	if m != nil {
		return m.OrderSn
	}
	return ""
}

type UserOrderInfoRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserOrderInfoRequest) Reset()         { *m = UserOrderInfoRequest{} }
func (m *UserOrderInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserOrderInfoRequest) ProtoMessage()    {}
func (*UserOrderInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{27}
}

func (m *UserOrderInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOrderInfoRequest.Unmarshal(m, b)
}
func (m *UserOrderInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOrderInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserOrderInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOrderInfoRequest.Merge(m, src)
}
func (m *UserOrderInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserOrderInfoRequest.Size(m)
}
func (m *UserOrderInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOrderInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserOrderInfoRequest proto.InternalMessageInfo

func (m *UserOrderInfoRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *UserOrderInfoRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserOrderInfoRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type OrderListResponse struct {
	Total                int32                `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*OrderInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderListResponse) Reset()         { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()    {}
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{28}
}

func (m *OrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListResponse.Unmarshal(m, b)
}
func (m *OrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListResponse.Marshal(b, m, deterministic)
}
func (m *OrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListResponse.Merge(m, src)
}
func (m *OrderListResponse) XXX_Size() int {
	return xxx_messageInfo_OrderListResponse.Size(m)
}
func (m *OrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListResponse proto.InternalMessageInfo

func (m *OrderListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OrderListResponse) GetData() []*OrderInfoResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderInfoRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderSn              string   `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfoRequest) Reset()         { *m = OrderInfoRequest{} }
func (m *OrderInfoRequest) String() string { return proto.CompactTextString(m) }
func (*OrderInfoRequest) ProtoMessage()    {}
func (*OrderInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{29}
}

func (m *OrderInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoRequest.Unmarshal(m, b)
}
func (m *OrderInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoRequest.Marshal(b, m, deterministic)
}
func (m *OrderInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoRequest.Merge(m, src)
}
func (m *OrderInfoRequest) XXX_Size() int {
	return xxx_messageInfo_OrderInfoRequest.Size(m)
}
func (m *OrderInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoRequest proto.InternalMessageInfo

func (m *OrderInfoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderInfoRequest) GetOrderSn() string {
	if m != nil {
		return m.OrderSn
	}
	return ""
}

type UpdateOrderRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OrderSn              string   `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderRequest) Reset()         { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()    {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{30}
}

func (m *UpdateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderRequest.Unmarshal(m, b)
}
func (m *UpdateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderRequest.Merge(m, src)
}
func (m *UpdateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderRequest.Size(m)
}
func (m *UpdateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderRequest proto.InternalMessageInfo

func (m *UpdateOrderRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateOrderRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateOrderRequest) GetOrderSn() string {
	if m != nil {
		return m.OrderSn
	}
	return ""
}

type DeleteOrderRequest struct {
	// 保证订单删除正确
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 int64    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Stock                int64    `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	TrustSn              string   `protobuf:"bytes,4,opt,name=trustSn,proto3" json:"trustSn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderRequest) Reset()         { *m = DeleteOrderRequest{} }
func (m *DeleteOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderRequest) ProtoMessage()    {}
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{31}
}

func (m *DeleteOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderRequest.Unmarshal(m, b)
}
func (m *DeleteOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderRequest.Merge(m, src)
}
func (m *DeleteOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderRequest.Size(m)
}
func (m *DeleteOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderRequest proto.InternalMessageInfo

func (m *DeleteOrderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteOrderRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *DeleteOrderRequest) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *DeleteOrderRequest) GetTrustSn() string {
	if m != nil {
		return m.TrustSn
	}
	return ""
}

type DeleteOrderResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderResponse) Reset()         { *m = DeleteOrderResponse{} }
func (m *DeleteOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderResponse) ProtoMessage()    {}
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{32}
}

func (m *DeleteOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderResponse.Unmarshal(m, b)
}
func (m *DeleteOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderResponse.Marshal(b, m, deterministic)
}
func (m *DeleteOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderResponse.Merge(m, src)
}
func (m *DeleteOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderResponse.Size(m)
}
func (m *DeleteOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderResponse proto.InternalMessageInfo

func (m *DeleteOrderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "order.Empty")
	proto.RegisterType((*IdRequest)(nil), "order.IdRequest")
	proto.RegisterType((*UserAccountResponse)(nil), "order.UserAccountResponse")
	proto.RegisterType((*CreateUserAccountInfo)(nil), "order.CreateUserAccountInfo")
	proto.RegisterType((*UpdateUserAccountInfo)(nil), "order.UpdateUserAccountInfo")
	proto.RegisterType((*DeleteUserAccountInfo)(nil), "order.DeleteUserAccountInfo")
	proto.RegisterType((*DeleteUserAccountResponse)(nil), "order.DeleteUserAccountResponse")
	proto.RegisterType((*PageInfo)(nil), "order.PageInfo")
	proto.RegisterType((*UserAccountListResponse)(nil), "order.UserAccountListResponse")
	proto.RegisterType((*HoldPositionRequest)(nil), "order.HoldPositionRequest")
	proto.RegisterType((*HoldPositionResponse)(nil), "order.HoldPositionResponse")
	proto.RegisterType((*CreateHoldPositionRequest)(nil), "order.CreateHoldPositionRequest")
	proto.RegisterType((*UpdateHoldPositionRequest)(nil), "order.UpdateHoldPositionRequest")
	proto.RegisterType((*DeleteHoldPositionRequest)(nil), "order.DeleteHoldPositionRequest")
	proto.RegisterType((*DeleteHoldPositionResponse)(nil), "order.DeleteHoldPositionResponse")
	proto.RegisterType((*UserHoldPositionRequest)(nil), "order.UserHoldPositionRequest")
	proto.RegisterType((*HoldPositionListResponse)(nil), "order.HoldPositionListResponse")
	proto.RegisterType((*TrustItemRequest)(nil), "order.TrustItemRequest")
	proto.RegisterType((*TrustInfoResponse)(nil), "order.TrustInfoResponse")
	proto.RegisterType((*UserTrustInfoRequest)(nil), "order.UserTrustInfoRequest")
	proto.RegisterType((*TrustListResponse)(nil), "order.TrustListResponse")
	proto.RegisterType((*TrustInfoRequest)(nil), "order.TrustInfoRequest")
	proto.RegisterType((*UpdateTrustRequest)(nil), "order.UpdateTrustRequest")
	proto.RegisterType((*DeleteTrustRequest)(nil), "order.DeleteTrustRequest")
	proto.RegisterType((*DeleteTrustResponse)(nil), "order.DeleteTrustResponse")
	proto.RegisterType((*OrderItemRequest)(nil), "order.OrderItemRequest")
	proto.RegisterType((*OrderInfoResponse)(nil), "order.OrderInfoResponse")
	proto.RegisterType((*UserOrderInfoRequest)(nil), "order.UserOrderInfoRequest")
	proto.RegisterType((*OrderListResponse)(nil), "order.OrderListResponse")
	proto.RegisterType((*OrderInfoRequest)(nil), "order.OrderInfoRequest")
	proto.RegisterType((*UpdateOrderRequest)(nil), "order.UpdateOrderRequest")
	proto.RegisterType((*DeleteOrderRequest)(nil), "order.DeleteOrderRequest")
	proto.RegisterType((*DeleteOrderResponse)(nil), "order.DeleteOrderResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 1062 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x51, 0x6f, 0xdc, 0x44,
	0x10, 0x96, 0xed, 0x73, 0x2e, 0x37, 0xd1, 0xe5, 0x9a, 0x4d, 0x42, 0x1d, 0xa7, 0x2a, 0x87, 0x05,
	0x52, 0x1e, 0x20, 0x41, 0x45, 0xf0, 0x84, 0x90, 0xaa, 0x26, 0xb4, 0x87, 0x4a, 0x5b, 0xf9, 0x68,
	0x10, 0xbc, 0x20, 0xe7, 0xbc, 0x29, 0x56, 0xef, 0x6c, 0x63, 0xef, 0x21, 0xc1, 0x3b, 0xbc, 0xf2,
	0xce, 0x7f, 0x40, 0xfc, 0x0e, 0xfe, 0x10, 0xcf, 0x68, 0xc7, 0xf6, 0x7a, 0xd7, 0x5e, 0x5f, 0x92,
	0x72, 0x88, 0x3c, 0xc5, 0xb3, 0xde, 0xfd, 0xf6, 0x9b, 0x99, 0x6f, 0x3c, 0x73, 0x81, 0xad, 0x24,
	0x0b, 0x69, 0x76, 0x9c, 0x66, 0x09, 0x4b, 0x88, 0x8d, 0x86, 0xd7, 0x07, 0xfb, 0x6c, 0x91, 0xb2,
	0x9f, 0xbc, 0x43, 0x18, 0x4c, 0x42, 0x9f, 0xfe, 0xb0, 0xa4, 0x39, 0x23, 0xdb, 0x60, 0x46, 0xa1,
	0x63, 0x8c, 0x8d, 0x23, 0xcb, 0x37, 0xa3, 0xd0, 0xfb, 0xc3, 0x80, 0xdd, 0x97, 0x39, 0xcd, 0x1e,
	0xce, 0x66, 0xc9, 0x32, 0x66, 0x3e, 0xcd, 0xd3, 0x24, 0xce, 0x29, 0x79, 0x0b, 0x36, 0x96, 0x39,
	0xcd, 0x26, 0xd5, 0xde, 0xd2, 0x22, 0x0e, 0xf4, 0x83, 0x62, 0xab, 0x63, 0x8e, 0x8d, 0x23, 0xd3,
	0xaf, 0x4c, 0x32, 0x86, 0xad, 0x45, 0x90, 0xbd, 0xa6, 0xec, 0x3c, 0x98, 0x2f, 0xa9, 0x63, 0xe1,
	0x5b, 0x79, 0x89, 0xdc, 0x83, 0x41, 0xf0, 0x63, 0x10, 0xcd, 0x83, 0x8b, 0x39, 0x75, 0x7a, 0xf8,
	0xbe, 0x5e, 0x20, 0xef, 0xc2, 0x30, 0xcd, 0x92, 0xcb, 0x88, 0x3d, 0x8c, 0xc3, 0xa7, 0x49, 0x9e,
	0x3b, 0x36, 0xee, 0x50, 0x17, 0xbd, 0x3f, 0x0d, 0xd8, 0x7f, 0x94, 0xd1, 0x80, 0x51, 0x89, 0xf5,
	0x24, 0xbe, 0x4c, 0x6e, 0x2d, 0xe3, 0x09, 0xec, 0xbf, 0x4c, 0xc3, 0x75, 0x10, 0xf6, 0x4e, 0x60,
	0xff, 0x94, 0xce, 0xe9, 0xb5, 0xa1, 0xbc, 0x8f, 0xe1, 0xa0, 0x75, 0x40, 0xa4, 0xd8, 0x81, 0x7e,
	0xbe, 0x9c, 0xcd, 0x68, 0x9e, 0xe3, 0xa9, 0x4d, 0xbf, 0x32, 0xbd, 0x0f, 0x61, 0xf3, 0x45, 0xf0,
	0x8a, 0x22, 0xf4, 0x36, 0x98, 0x69, 0x8c, 0x1b, 0x86, 0xbe, 0x99, 0xc6, 0x64, 0x0f, 0xec, 0x74,
	0x1a, 0xfd, 0x4c, 0x91, 0xdb, 0xd0, 0x2f, 0x0c, 0xef, 0x3b, 0xb8, 0x2b, 0x5d, 0xf1, 0x34, 0xca,
	0xeb, 0x6b, 0xf6, 0xc0, 0x66, 0x09, 0x0b, 0xe6, 0x88, 0x61, 0xfb, 0x85, 0x41, 0x8e, 0xa1, 0x17,
	0x06, 0x2c, 0x70, 0xcc, 0xb1, 0x75, 0xb4, 0xf5, 0xc0, 0x3d, 0x2e, 0x04, 0xac, 0xa1, 0xe9, 0xe3,
	0x3e, 0xef, 0x3d, 0xd8, 0x7d, 0x92, 0xcc, 0xc3, 0x17, 0x49, 0x1e, 0xb1, 0x28, 0x89, 0xbb, 0xe4,
	0xfc, 0xbb, 0x01, 0x7b, 0xea, 0xbe, 0x92, 0x45, 0x63, 0x23, 0x21, 0xd0, 0xe3, 0x31, 0x42, 0x2f,
	0x2c, 0x1f, 0x9f, 0x39, 0xd3, 0x9c, 0x25, 0xb3, 0xd7, 0xa8, 0x04, 0xcb, 0x2f, 0x0c, 0xae, 0x01,
	0x7c, 0x78, 0x16, 0x2c, 0x0a, 0x0d, 0x0c, 0xfc, 0x7a, 0x81, 0x47, 0x3e, 0x5e, 0x2e, 0x2e, 0x68,
	0x86, 0xc9, 0xb7, 0xfd, 0xd2, 0xe2, 0xf8, 0xb3, 0x24, 0x67, 0xce, 0x06, 0x66, 0x10, 0x9f, 0xbd,
	0xdf, 0x0c, 0x38, 0x28, 0xb4, 0xab, 0x73, 0xa5, 0x62, 0x64, 0xe8, 0x18, 0x99, 0x9d, 0x8c, 0xac,
	0x6e, 0x46, 0x3d, 0x2d, 0x23, 0xbb, 0xc1, 0xa8, 0x10, 0xe7, 0x6d, 0x61, 0x74, 0x56, 0x29, 0xf6,
	0x5f, 0x11, 0xf2, 0x3e, 0x01, 0x57, 0x07, 0x73, 0xa5, 0xf2, 0x3f, 0x28, 0x74, 0x7c, 0xcd, 0xcb,
	0xbd, 0x00, 0x1c, 0x79, 0xeb, 0x35, 0x74, 0x7f, 0xa2, 0xe8, 0xfe, 0xb0, 0xd4, 0xbd, 0x8e, 0x65,
	0x29, 0xfc, 0x5f, 0x0d, 0xb8, 0xf3, 0x55, 0xb6, 0xcc, 0xd9, 0x84, 0xd1, 0xc5, 0xcd, 0x33, 0x73,
	0x83, 0xd8, 0xf3, 0x2c, 0x86, 0x51, 0x46, 0x67, 0x9c, 0x05, 0x0a, 0x77, 0xe8, 0xd7, 0x0b, 0xde,
	0x2f, 0x26, 0xec, 0x14, 0x44, 0xe2, 0xcb, 0x64, 0x0d, 0x75, 0xb5, 0x36, 0x66, 0xe4, 0x3e, 0x40,
	0x48, 0x83, 0xf9, 0xb3, 0x02, 0xad, 0x8f, 0x68, 0xd2, 0x0a, 0x71, 0x61, 0x93, 0x5b, 0x8f, 0x38,
	0xea, 0x26, 0xa2, 0x0a, 0x9b, 0xb3, 0xc8, 0x59, 0xc0, 0x96, 0xb9, 0x33, 0x40, 0xd9, 0x96, 0x16,
	0x97, 0x08, 0xe3, 0xce, 0x4e, 0x63, 0x07, 0xf0, 0x45, 0x65, 0x7a, 0xdf, 0xc2, 0x1e, 0x97, 0x88,
	0x14, 0x8a, 0xee, 0x9c, 0x10, 0xe8, 0xa5, 0xc1, 0xab, 0xe2, 0x5b, 0x69, 0xfb, 0xf8, 0xcc, 0xd9,
	0xf0, 0xbf, 0xf8, 0x0d, 0xb5, 0x70, 0x5d, 0xd8, 0xde, 0xd7, 0x65, 0x88, 0xaf, 0x21, 0xa4, 0xf7,
	0x15, 0x21, 0x39, 0xa5, 0x90, 0x5a, 0x09, 0x2a, 0x55, 0xf4, 0x69, 0x25, 0x22, 0x89, 0x70, 0x33,
	0x75, 0x92, 0xcb, 0xa6, 0xea, 0xf2, 0x39, 0x90, 0xe2, 0x2b, 0x81, 0x18, 0xed, 0xf3, 0x36, 0x9e,
	0xaf, 0x43, 0x69, 0x76, 0x85, 0xd2, 0x52, 0x71, 0xbf, 0x07, 0x52, 0x54, 0x69, 0x07, 0xee, 0x4d,
	0x25, 0x25, 0xdd, 0xd4, 0x53, 0x6f, 0x3a, 0x81, 0x5d, 0xe5, 0xa6, 0x2b, 0x3f, 0x04, 0xbc, 0xec,
	0x9e, 0xf3, 0x90, 0xfe, 0xdf, 0x65, 0xf7, 0x97, 0x01, 0x3b, 0x05, 0x91, 0xdb, 0x56, 0x76, 0x75,
	0xbe, 0xfb, 0xcd, 0x7c, 0xa3, 0x18, 0xa7, 0x31, 0x56, 0xdb, 0xc0, 0xaf, 0xcc, 0xaa, 0x74, 0x24,
	0x77, 0xd6, 0x5a, 0x3a, 0x88, 0xfb, 0xc6, 0xa5, 0xd3, 0x0a, 0x72, 0x5d, 0x3a, 0x2d, 0xc2, 0x9a,
	0xd2, 0x79, 0x5e, 0xba, 0x5c, 0x96, 0x4e, 0x69, 0xd6, 0xa5, 0x83, 0x0b, 0x6f, 0x50, 0x3a, 0x55,
	0x28, 0x2d, 0x35, 0x94, 0xa2, 0x74, 0x3a, 0x70, 0xff, 0x83, 0xd2, 0x29, 0x6f, 0xba, 0xaa, 0x74,
	0x1e, 0xfc, 0xbd, 0x05, 0x36, 0xee, 0x25, 0x9f, 0xc1, 0xf6, 0x63, 0xca, 0xa4, 0xa1, 0x8e, 0xdc,
	0x29, 0x83, 0x2d, 0x7e, 0x90, 0xb8, 0x2b, 0x46, 0x3f, 0xf2, 0x25, 0xec, 0xb4, 0x66, 0x7d, 0x72,
	0xaf, 0x3c, 0xa0, 0xfd, 0x15, 0x70, 0x15, 0x5c, 0x6b, 0x12, 0x17, 0x70, 0xda, 0x19, 0x7d, 0x25,
	0xdc, 0x19, 0x10, 0xd5, 0x3b, 0x2e, 0x3d, 0x32, 0x2a, 0x4f, 0x54, 0x03, 0xb4, 0x7b, 0xbf, 0x0d,
	0xa1, 0x68, 0x74, 0x0a, 0x3b, 0xad, 0x19, 0x5d, 0xb0, 0xd2, 0x8e, 0xfb, 0xee, 0xb8, 0xeb, 0xad,
	0x00, 0xfd, 0x02, 0x46, 0x8f, 0x29, 0x93, 0xc7, 0x0a, 0xe2, 0x6a, 0x67, 0x8d, 0x22, 0x09, 0xab,
	0xe6, 0x10, 0x72, 0x0e, 0xbb, 0x0d, 0x2c, 0x74, 0x54, 0xf6, 0x4b, 0x87, 0xf9, 0xb6, 0x06, 0xb3,
	0xe1, 0x38, 0x69, 0x4f, 0xc3, 0x64, 0xac, 0xa4, 0xf7, 0xc6, 0x64, 0xa7, 0x55, 0xbd, 0x69, 0x41,
	0x3b, 0x67, 0xdd, 0xd5, 0xa0, 0xdf, 0x54, 0xc5, 0xa6, 0x05, 0xed, 0x9c, 0x57, 0xdd, 0x77, 0x56,
	0xec, 0x28, 0xa1, 0x4f, 0x61, 0x54, 0x78, 0x2a, 0x66, 0x3c, 0x72, 0x57, 0xe9, 0xe5, 0x75, 0xfb,
	0x71, 0x3b, 0x9b, 0x3c, 0xf9, 0x1c, 0x86, 0x62, 0x37, 0x26, 0xe7, 0x50, 0x4a, 0x4e, 0xb3, 0xf1,
	0xab, 0x38, 0x4a, 0x4a, 0x4e, 0x61, 0x24, 0x70, 0x4e, 0x29, 0x0b, 0xa2, 0x79, 0x83, 0x4d, 0x17,
	0x4a, 0x83, 0xcd, 0x48, 0x1a, 0x17, 0xd0, 0xa7, 0x03, 0x25, 0x01, 0x72, 0xbb, 0x5f, 0x81, 0xf3,
	0x04, 0x46, 0x52, 0xd3, 0x56, 0x70, 0xda, 0x63, 0x83, 0x28, 0x55, 0x5d, 0x9f, 0x17, 0x51, 0x16,
	0x2d, 0x5d, 0xf8, 0xd5, 0x6c, 0xf2, 0x6e, 0x67, 0x3f, 0xe0, 0x51, 0x16, 0xbb, 0x5b, 0x51, 0x6e,
	0xf6, 0x08, 0x15, 0xa7, 0x19, 0x65, 0x81, 0xd3, 0x88, 0xf2, 0x6a, 0x14, 0x7d, 0x94, 0x6b, 0x9f,
	0xd4, 0x28, 0xcb, 0x9d, 0x61, 0x05, 0x8e, 0x88, 0x72, 0x1b, 0xa7, 0xdd, 0x61, 0x1a, 0x51, 0x56,
	0x5a, 0xc2, 0xc5, 0x06, 0xfe, 0xff, 0xe9, 0xa3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x06,
	0x10, 0x70, 0x8e, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	// 账户相关
	GetUserAccount(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserAccountResponse, error)
	CreateUserAccount(ctx context.Context, in *CreateUserAccountInfo, opts ...grpc.CallOption) (*UserAccountResponse, error)
	UpdateUserAccount(ctx context.Context, in *UpdateUserAccountInfo, opts ...grpc.CallOption) (*UserAccountResponse, error)
	GetUserAccountList(ctx context.Context, in *PageInfo, opts ...grpc.CallOption) (*UserAccountListResponse, error)
	DeleteUserAccount(ctx context.Context, in *DeleteUserAccountInfo, opts ...grpc.CallOption) (*DeleteUserAccountResponse, error)
	// 持仓相关
	// 用户 和 股票 多对多的 关系
	GetHoldPosition(ctx context.Context, in *HoldPositionRequest, opts ...grpc.CallOption) (*HoldPositionResponse, error)
	GetHoldPositionList(ctx context.Context, in *UserHoldPositionRequest, opts ...grpc.CallOption) (*HoldPositionListResponse, error)
	// 实际上用户是不能直接操作下面这三个方法的 这里写出来只是当作思路  ==== 所以在rpc中并没有写出这三个的逻辑 ====
	// 在创建委托 并且成交时 利用model 进行更新 下面三个
	CreateHoldPosition(ctx context.Context, in *CreateHoldPositionRequest, opts ...grpc.CallOption) (*HoldPositionResponse, error)
	UpdateHoldPosition(ctx context.Context, in *UpdateHoldPositionRequest, opts ...grpc.CallOption) (*HoldPositionResponse, error)
	// 卖出的时候 正好一点不留 就用delete
	DeleteHoldPosition(ctx context.Context, in *DeleteHoldPositionRequest, opts ...grpc.CallOption) (*DeleteHoldPositionResponse, error)
	// 委托相关
	CreateTrustItem(ctx context.Context, in *TrustItemRequest, opts ...grpc.CallOption) (*TrustInfoResponse, error)
	TrustItemList(ctx context.Context, in *UserTrustInfoRequest, opts ...grpc.CallOption) (*TrustListResponse, error)
	TrustItemDetail(ctx context.Context, in *TrustInfoRequest, opts ...grpc.CallOption) (*TrustInfoResponse, error)
	UpdateTrustItem(ctx context.Context, in *UpdateTrustRequest, opts ...grpc.CallOption) (*TrustInfoResponse, error)
	DeleteTrustItem(ctx context.Context, in *DeleteTrustRequest, opts ...grpc.CallOption) (*DeleteTrustResponse, error)
	// 订单相关
	CreateOrderItem(ctx context.Context, in *OrderItemRequest, opts ...grpc.CallOption) (*OrderInfoResponse, error)
	OrderItemList(ctx context.Context, in *UserOrderInfoRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
	OrderItemDetail(ctx context.Context, in *OrderInfoRequest, opts ...grpc.CallOption) (*OrderInfoResponse, error)
	UpdateOrderItem(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*OrderInfoResponse, error)
	DeleteOrderItem(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*DeleteOrderResponse, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) GetUserAccount(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserAccountResponse, error) {
	out := new(UserAccountResponse)
	err := c.cc.Invoke(ctx, "/order.Order/GetUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateUserAccount(ctx context.Context, in *CreateUserAccountInfo, opts ...grpc.CallOption) (*UserAccountResponse, error) {
	out := new(UserAccountResponse)
	err := c.cc.Invoke(ctx, "/order.Order/CreateUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateUserAccount(ctx context.Context, in *UpdateUserAccountInfo, opts ...grpc.CallOption) (*UserAccountResponse, error) {
	out := new(UserAccountResponse)
	err := c.cc.Invoke(ctx, "/order.Order/UpdateUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetUserAccountList(ctx context.Context, in *PageInfo, opts ...grpc.CallOption) (*UserAccountListResponse, error) {
	out := new(UserAccountListResponse)
	err := c.cc.Invoke(ctx, "/order.Order/GetUserAccountList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) DeleteUserAccount(ctx context.Context, in *DeleteUserAccountInfo, opts ...grpc.CallOption) (*DeleteUserAccountResponse, error) {
	out := new(DeleteUserAccountResponse)
	err := c.cc.Invoke(ctx, "/order.Order/DeleteUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetHoldPosition(ctx context.Context, in *HoldPositionRequest, opts ...grpc.CallOption) (*HoldPositionResponse, error) {
	out := new(HoldPositionResponse)
	err := c.cc.Invoke(ctx, "/order.Order/GetHoldPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetHoldPositionList(ctx context.Context, in *UserHoldPositionRequest, opts ...grpc.CallOption) (*HoldPositionListResponse, error) {
	out := new(HoldPositionListResponse)
	err := c.cc.Invoke(ctx, "/order.Order/GetHoldPositionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateHoldPosition(ctx context.Context, in *CreateHoldPositionRequest, opts ...grpc.CallOption) (*HoldPositionResponse, error) {
	out := new(HoldPositionResponse)
	err := c.cc.Invoke(ctx, "/order.Order/CreateHoldPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateHoldPosition(ctx context.Context, in *UpdateHoldPositionRequest, opts ...grpc.CallOption) (*HoldPositionResponse, error) {
	out := new(HoldPositionResponse)
	err := c.cc.Invoke(ctx, "/order.Order/UpdateHoldPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) DeleteHoldPosition(ctx context.Context, in *DeleteHoldPositionRequest, opts ...grpc.CallOption) (*DeleteHoldPositionResponse, error) {
	out := new(DeleteHoldPositionResponse)
	err := c.cc.Invoke(ctx, "/order.Order/DeleteHoldPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateTrustItem(ctx context.Context, in *TrustItemRequest, opts ...grpc.CallOption) (*TrustInfoResponse, error) {
	out := new(TrustInfoResponse)
	err := c.cc.Invoke(ctx, "/order.Order/CreateTrustItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) TrustItemList(ctx context.Context, in *UserTrustInfoRequest, opts ...grpc.CallOption) (*TrustListResponse, error) {
	out := new(TrustListResponse)
	err := c.cc.Invoke(ctx, "/order.Order/TrustItemList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) TrustItemDetail(ctx context.Context, in *TrustInfoRequest, opts ...grpc.CallOption) (*TrustInfoResponse, error) {
	out := new(TrustInfoResponse)
	err := c.cc.Invoke(ctx, "/order.Order/TrustItemDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateTrustItem(ctx context.Context, in *UpdateTrustRequest, opts ...grpc.CallOption) (*TrustInfoResponse, error) {
	out := new(TrustInfoResponse)
	err := c.cc.Invoke(ctx, "/order.Order/UpdateTrustItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) DeleteTrustItem(ctx context.Context, in *DeleteTrustRequest, opts ...grpc.CallOption) (*DeleteTrustResponse, error) {
	out := new(DeleteTrustResponse)
	err := c.cc.Invoke(ctx, "/order.Order/DeleteTrustItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrderItem(ctx context.Context, in *OrderItemRequest, opts ...grpc.CallOption) (*OrderInfoResponse, error) {
	out := new(OrderInfoResponse)
	err := c.cc.Invoke(ctx, "/order.Order/CreateOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) OrderItemList(ctx context.Context, in *UserOrderInfoRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	out := new(OrderListResponse)
	err := c.cc.Invoke(ctx, "/order.Order/OrderItemList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) OrderItemDetail(ctx context.Context, in *OrderInfoRequest, opts ...grpc.CallOption) (*OrderInfoResponse, error) {
	out := new(OrderInfoResponse)
	err := c.cc.Invoke(ctx, "/order.Order/OrderItemDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateOrderItem(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*OrderInfoResponse, error) {
	out := new(OrderInfoResponse)
	err := c.cc.Invoke(ctx, "/order.Order/UpdateOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) DeleteOrderItem(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*DeleteOrderResponse, error) {
	out := new(DeleteOrderResponse)
	err := c.cc.Invoke(ctx, "/order.Order/DeleteOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	// 账户相关
	GetUserAccount(context.Context, *IdRequest) (*UserAccountResponse, error)
	CreateUserAccount(context.Context, *CreateUserAccountInfo) (*UserAccountResponse, error)
	UpdateUserAccount(context.Context, *UpdateUserAccountInfo) (*UserAccountResponse, error)
	GetUserAccountList(context.Context, *PageInfo) (*UserAccountListResponse, error)
	DeleteUserAccount(context.Context, *DeleteUserAccountInfo) (*DeleteUserAccountResponse, error)
	// 持仓相关
	// 用户 和 股票 多对多的 关系
	GetHoldPosition(context.Context, *HoldPositionRequest) (*HoldPositionResponse, error)
	GetHoldPositionList(context.Context, *UserHoldPositionRequest) (*HoldPositionListResponse, error)
	// 实际上用户是不能直接操作下面这三个方法的 这里写出来只是当作思路  ==== 所以在rpc中并没有写出这三个的逻辑 ====
	// 在创建委托 并且成交时 利用model 进行更新 下面三个
	CreateHoldPosition(context.Context, *CreateHoldPositionRequest) (*HoldPositionResponse, error)
	UpdateHoldPosition(context.Context, *UpdateHoldPositionRequest) (*HoldPositionResponse, error)
	// 卖出的时候 正好一点不留 就用delete
	DeleteHoldPosition(context.Context, *DeleteHoldPositionRequest) (*DeleteHoldPositionResponse, error)
	// 委托相关
	CreateTrustItem(context.Context, *TrustItemRequest) (*TrustInfoResponse, error)
	TrustItemList(context.Context, *UserTrustInfoRequest) (*TrustListResponse, error)
	TrustItemDetail(context.Context, *TrustInfoRequest) (*TrustInfoResponse, error)
	UpdateTrustItem(context.Context, *UpdateTrustRequest) (*TrustInfoResponse, error)
	DeleteTrustItem(context.Context, *DeleteTrustRequest) (*DeleteTrustResponse, error)
	// 订单相关
	CreateOrderItem(context.Context, *OrderItemRequest) (*OrderInfoResponse, error)
	OrderItemList(context.Context, *UserOrderInfoRequest) (*OrderListResponse, error)
	OrderItemDetail(context.Context, *OrderInfoRequest) (*OrderInfoResponse, error)
	UpdateOrderItem(context.Context, *UpdateOrderRequest) (*OrderInfoResponse, error)
	DeleteOrderItem(context.Context, *DeleteOrderRequest) (*DeleteOrderResponse, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) GetUserAccount(ctx context.Context, req *IdRequest) (*UserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAccount not implemented")
}
func (*UnimplementedOrderServer) CreateUserAccount(ctx context.Context, req *CreateUserAccountInfo) (*UserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAccount not implemented")
}
func (*UnimplementedOrderServer) UpdateUserAccount(ctx context.Context, req *UpdateUserAccountInfo) (*UserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAccount not implemented")
}
func (*UnimplementedOrderServer) GetUserAccountList(ctx context.Context, req *PageInfo) (*UserAccountListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAccountList not implemented")
}
func (*UnimplementedOrderServer) DeleteUserAccount(ctx context.Context, req *DeleteUserAccountInfo) (*DeleteUserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserAccount not implemented")
}
func (*UnimplementedOrderServer) GetHoldPosition(ctx context.Context, req *HoldPositionRequest) (*HoldPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHoldPosition not implemented")
}
func (*UnimplementedOrderServer) GetHoldPositionList(ctx context.Context, req *UserHoldPositionRequest) (*HoldPositionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHoldPositionList not implemented")
}
func (*UnimplementedOrderServer) CreateHoldPosition(ctx context.Context, req *CreateHoldPositionRequest) (*HoldPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHoldPosition not implemented")
}
func (*UnimplementedOrderServer) UpdateHoldPosition(ctx context.Context, req *UpdateHoldPositionRequest) (*HoldPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHoldPosition not implemented")
}
func (*UnimplementedOrderServer) DeleteHoldPosition(ctx context.Context, req *DeleteHoldPositionRequest) (*DeleteHoldPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHoldPosition not implemented")
}
func (*UnimplementedOrderServer) CreateTrustItem(ctx context.Context, req *TrustItemRequest) (*TrustInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrustItem not implemented")
}
func (*UnimplementedOrderServer) TrustItemList(ctx context.Context, req *UserTrustInfoRequest) (*TrustListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrustItemList not implemented")
}
func (*UnimplementedOrderServer) TrustItemDetail(ctx context.Context, req *TrustInfoRequest) (*TrustInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrustItemDetail not implemented")
}
func (*UnimplementedOrderServer) UpdateTrustItem(ctx context.Context, req *UpdateTrustRequest) (*TrustInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrustItem not implemented")
}
func (*UnimplementedOrderServer) DeleteTrustItem(ctx context.Context, req *DeleteTrustRequest) (*DeleteTrustResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrustItem not implemented")
}
func (*UnimplementedOrderServer) CreateOrderItem(ctx context.Context, req *OrderItemRequest) (*OrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderItem not implemented")
}
func (*UnimplementedOrderServer) OrderItemList(ctx context.Context, req *UserOrderInfoRequest) (*OrderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderItemList not implemented")
}
func (*UnimplementedOrderServer) OrderItemDetail(ctx context.Context, req *OrderInfoRequest) (*OrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderItemDetail not implemented")
}
func (*UnimplementedOrderServer) UpdateOrderItem(ctx context.Context, req *UpdateOrderRequest) (*OrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderItem not implemented")
}
func (*UnimplementedOrderServer) DeleteOrderItem(ctx context.Context, req *DeleteOrderRequest) (*DeleteOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrderItem not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_GetUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetUserAccount(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAccountInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateUserAccount(ctx, req.(*CreateUserAccountInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAccountInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/UpdateUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateUserAccount(ctx, req.(*UpdateUserAccountInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetUserAccountList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetUserAccountList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetUserAccountList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetUserAccountList(ctx, req.(*PageInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_DeleteUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserAccountInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).DeleteUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/DeleteUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).DeleteUserAccount(ctx, req.(*DeleteUserAccountInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetHoldPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetHoldPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetHoldPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetHoldPosition(ctx, req.(*HoldPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetHoldPositionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserHoldPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetHoldPositionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetHoldPositionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetHoldPositionList(ctx, req.(*UserHoldPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateHoldPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHoldPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateHoldPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateHoldPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateHoldPosition(ctx, req.(*CreateHoldPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateHoldPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHoldPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateHoldPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/UpdateHoldPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateHoldPosition(ctx, req.(*UpdateHoldPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_DeleteHoldPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHoldPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).DeleteHoldPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/DeleteHoldPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).DeleteHoldPosition(ctx, req.(*DeleteHoldPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateTrustItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrustItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateTrustItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateTrustItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateTrustItem(ctx, req.(*TrustItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_TrustItemList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTrustInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).TrustItemList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/TrustItemList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).TrustItemList(ctx, req.(*UserTrustInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_TrustItemDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrustInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).TrustItemDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/TrustItemDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).TrustItemDetail(ctx, req.(*TrustInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateTrustItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateTrustItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/UpdateTrustItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateTrustItem(ctx, req.(*UpdateTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_DeleteTrustItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).DeleteTrustItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/DeleteTrustItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).DeleteTrustItem(ctx, req.(*DeleteTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrderItem(ctx, req.(*OrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_OrderItemList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).OrderItemList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/OrderItemList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).OrderItemList(ctx, req.(*UserOrderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_OrderItemDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).OrderItemDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/OrderItemDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).OrderItemDetail(ctx, req.(*OrderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/UpdateOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateOrderItem(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_DeleteOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).DeleteOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/DeleteOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).DeleteOrderItem(ctx, req.(*DeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAccount",
			Handler:    _Order_GetUserAccount_Handler,
		},
		{
			MethodName: "CreateUserAccount",
			Handler:    _Order_CreateUserAccount_Handler,
		},
		{
			MethodName: "UpdateUserAccount",
			Handler:    _Order_UpdateUserAccount_Handler,
		},
		{
			MethodName: "GetUserAccountList",
			Handler:    _Order_GetUserAccountList_Handler,
		},
		{
			MethodName: "DeleteUserAccount",
			Handler:    _Order_DeleteUserAccount_Handler,
		},
		{
			MethodName: "GetHoldPosition",
			Handler:    _Order_GetHoldPosition_Handler,
		},
		{
			MethodName: "GetHoldPositionList",
			Handler:    _Order_GetHoldPositionList_Handler,
		},
		{
			MethodName: "CreateHoldPosition",
			Handler:    _Order_CreateHoldPosition_Handler,
		},
		{
			MethodName: "UpdateHoldPosition",
			Handler:    _Order_UpdateHoldPosition_Handler,
		},
		{
			MethodName: "DeleteHoldPosition",
			Handler:    _Order_DeleteHoldPosition_Handler,
		},
		{
			MethodName: "CreateTrustItem",
			Handler:    _Order_CreateTrustItem_Handler,
		},
		{
			MethodName: "TrustItemList",
			Handler:    _Order_TrustItemList_Handler,
		},
		{
			MethodName: "TrustItemDetail",
			Handler:    _Order_TrustItemDetail_Handler,
		},
		{
			MethodName: "UpdateTrustItem",
			Handler:    _Order_UpdateTrustItem_Handler,
		},
		{
			MethodName: "DeleteTrustItem",
			Handler:    _Order_DeleteTrustItem_Handler,
		},
		{
			MethodName: "CreateOrderItem",
			Handler:    _Order_CreateOrderItem_Handler,
		},
		{
			MethodName: "OrderItemList",
			Handler:    _Order_OrderItemList_Handler,
		},
		{
			MethodName: "OrderItemDetail",
			Handler:    _Order_OrderItemDetail_Handler,
		},
		{
			MethodName: "UpdateOrderItem",
			Handler:    _Order_UpdateOrderItem_Handler,
		},
		{
			MethodName: "DeleteOrderItem",
			Handler:    _Order_DeleteOrderItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
