// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operation.proto

package operation

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type UserFavRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	StockId              int32    `protobuf:"varint,2,opt,name=stockId,proto3" json:"stockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFavRequest) Reset()         { *m = UserFavRequest{} }
func (m *UserFavRequest) String() string { return proto.CompactTextString(m) }
func (*UserFavRequest) ProtoMessage()    {}
func (*UserFavRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{1}
}

func (m *UserFavRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFavRequest.Unmarshal(m, b)
}
func (m *UserFavRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFavRequest.Marshal(b, m, deterministic)
}
func (m *UserFavRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFavRequest.Merge(m, src)
}
func (m *UserFavRequest) XXX_Size() int {
	return xxx_messageInfo_UserFavRequest.Size(m)
}
func (m *UserFavRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFavRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserFavRequest proto.InternalMessageInfo

func (m *UserFavRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserFavRequest) GetStockId() int32 {
	if m != nil {
		return m.StockId
	}
	return 0
}

type UserFavResponse struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	StockId              int32    `protobuf:"varint,2,opt,name=stockId,proto3" json:"stockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFavResponse) Reset()         { *m = UserFavResponse{} }
func (m *UserFavResponse) String() string { return proto.CompactTextString(m) }
func (*UserFavResponse) ProtoMessage()    {}
func (*UserFavResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{2}
}

func (m *UserFavResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFavResponse.Unmarshal(m, b)
}
func (m *UserFavResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFavResponse.Marshal(b, m, deterministic)
}
func (m *UserFavResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFavResponse.Merge(m, src)
}
func (m *UserFavResponse) XXX_Size() int {
	return xxx_messageInfo_UserFavResponse.Size(m)
}
func (m *UserFavResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFavResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserFavResponse proto.InternalMessageInfo

func (m *UserFavResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserFavResponse) GetStockId() int32 {
	if m != nil {
		return m.StockId
	}
	return 0
}

type UserFavListResponse struct {
	Total                int32              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*UserFavResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UserFavListResponse) Reset()         { *m = UserFavListResponse{} }
func (m *UserFavListResponse) String() string { return proto.CompactTextString(m) }
func (*UserFavListResponse) ProtoMessage()    {}
func (*UserFavListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{3}
}

func (m *UserFavListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFavListResponse.Unmarshal(m, b)
}
func (m *UserFavListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFavListResponse.Marshal(b, m, deterministic)
}
func (m *UserFavListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFavListResponse.Merge(m, src)
}
func (m *UserFavListResponse) XXX_Size() int {
	return xxx_messageInfo_UserFavListResponse.Size(m)
}
func (m *UserFavListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFavListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserFavListResponse proto.InternalMessageInfo

func (m *UserFavListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserFavListResponse) GetData() []*UserFavResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "operation.Empty")
	proto.RegisterType((*UserFavRequest)(nil), "operation.UserFavRequest")
	proto.RegisterType((*UserFavResponse)(nil), "operation.UserFavResponse")
	proto.RegisterType((*UserFavListResponse)(nil), "operation.UserFavListResponse")
}

func init() { proto.RegisterFile("operation.proto", fileDescriptor_619dee0fded31cb3) }

var fileDescriptor_619dee0fded31cb3 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x2f, 0x48, 0x2d,
	0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94, 0x54, 0x2a, 0x39, 0x71, 0xf1, 0x85, 0x16, 0xa7, 0x16,
	0xb9, 0x25, 0x96, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x71, 0xb1, 0x95, 0x16,
	0xa7, 0x16, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x42, 0x12, 0x5c,
	0xec, 0xc5, 0x25, 0xf9, 0xc9, 0xd9, 0x9e, 0x29, 0x12, 0x4c, 0x60, 0x09, 0x18, 0x57, 0xc9, 0x99,
	0x8b, 0x1f, 0x6e, 0x46, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x19, 0x86, 0x44, 0x73, 0x09, 0x43,
	0x0d, 0xf1, 0xc9, 0x2c, 0x2e, 0x81, 0x1b, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x5f, 0x92, 0x98, 0x03,
	0x35, 0x07, 0xc2, 0x11, 0xd2, 0xe3, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x52, 0x60, 0xd6,
	0xe0, 0x36, 0x92, 0xd2, 0x43, 0xf8, 0x14, 0xcd, 0x21, 0x41, 0x60, 0x75, 0x46, 0x7d, 0x4c, 0x5c,
	0x08, 0xcf, 0x0b, 0xb9, 0x73, 0x71, 0xb9, 0xa7, 0x96, 0x40, 0x6d, 0x12, 0x92, 0xc4, 0xa6, 0x1b,
	0x1c, 0x14, 0x52, 0x72, 0x98, 0x52, 0x28, 0x8e, 0xb3, 0xe4, 0xe2, 0x72, 0x4c, 0x49, 0x81, 0xca,
	0xe0, 0x33, 0x48, 0x00, 0x49, 0x0a, 0x1c, 0xee, 0x42, 0x36, 0x5c, 0xbc, 0x2e, 0xa9, 0x39, 0xa9,
	0x25, 0xa9, 0x64, 0xe9, 0xb6, 0xe7, 0x12, 0x70, 0x4f, 0x2d, 0x81, 0x2a, 0x73, 0x49, 0x2d, 0x49,
	0xcc, 0xcc, 0x21, 0xc9, 0x80, 0x24, 0x36, 0x70, 0x8a, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x2c, 0x9e, 0x52, 0xa9, 0x24, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OperationClient is the client API for Operation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OperationClient interface {
	GetFavList(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavListResponse, error)
	AddUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserFavDetail(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error)
}

type operationClient struct {
	cc *grpc.ClientConn
}

func NewOperationClient(cc *grpc.ClientConn) OperationClient {
	return &operationClient{cc}
}

func (c *operationClient) GetFavList(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavListResponse, error) {
	out := new(UserFavListResponse)
	err := c.cc.Invoke(ctx, "/operation.operation/GetFavList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationClient) AddUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/operation.operation/AddUserFav", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationClient) DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/operation.operation/DeleteUserFav", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationClient) GetUserFavDetail(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/operation.operation/GetUserFavDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationServer is the server API for Operation service.
type OperationServer interface {
	GetFavList(context.Context, *UserFavRequest) (*UserFavListResponse, error)
	AddUserFav(context.Context, *UserFavRequest) (*Empty, error)
	DeleteUserFav(context.Context, *UserFavRequest) (*Empty, error)
	GetUserFavDetail(context.Context, *UserFavRequest) (*Empty, error)
}

// UnimplementedOperationServer can be embedded to have forward compatible implementations.
type UnimplementedOperationServer struct {
}

func (*UnimplementedOperationServer) GetFavList(ctx context.Context, req *UserFavRequest) (*UserFavListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavList not implemented")
}
func (*UnimplementedOperationServer) AddUserFav(ctx context.Context, req *UserFavRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserFav not implemented")
}
func (*UnimplementedOperationServer) DeleteUserFav(ctx context.Context, req *UserFavRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserFav not implemented")
}
func (*UnimplementedOperationServer) GetUserFavDetail(ctx context.Context, req *UserFavRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFavDetail not implemented")
}

func RegisterOperationServer(s *grpc.Server, srv OperationServer) {
	s.RegisterService(&_Operation_serviceDesc, srv)
}

func _Operation_GetFavList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServer).GetFavList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.operation/GetFavList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServer).GetFavList(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operation_AddUserFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServer).AddUserFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.operation/AddUserFav",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServer).AddUserFav(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operation_DeleteUserFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServer).DeleteUserFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.operation/DeleteUserFav",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServer).DeleteUserFav(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operation_GetUserFavDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServer).GetUserFavDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.operation/GetUserFavDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServer).GetUserFavDetail(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Operation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "operation.operation",
	HandlerType: (*OperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFavList",
			Handler:    _Operation_GetFavList_Handler,
		},
		{
			MethodName: "AddUserFav",
			Handler:    _Operation_AddUserFav_Handler,
		},
		{
			MethodName: "DeleteUserFav",
			Handler:    _Operation_DeleteUserFav_Handler,
		},
		{
			MethodName: "GetUserFavDetail",
			Handler:    _Operation_GetUserFavDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operation.proto",
}
